apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: uuzwshhxu-python 
  janus-idp.io/tekton: uuzwshhxu-python
  backstage.io/kubernetes-id: uuzwshhxu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uuzwshhxu-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  