apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: uuzwshhxu-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-2218ac6c2a.qj22.p3.openshiftapps.com/rhtap/rhtap-qe:e62b5af537ea39c6b41e88af334bbd96dc31ed67@sha256:9b8afc2ac43d4706b4547f779343b891104445a80301dcc9eeb3593722783f30
          name: container-image
